name: Nightly API Test & Publish Allure Report

on:
  schedule:
    - cron: '0 18 * * *'  # very day at 18:00 UTC, which is 02:00 Beijing time.
  workflow_dispatch:       # Manual Trigger

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Run Tests and Generate Allure Report
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh

      - name: Deploy Allure Report to Public Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: your-username/allure-report-host
          publish_branch: gh-pages
          publish_dir: ./allure-report
          personal_token: ${{ secrets.REPORT_TOKEN }}